### PR TITLE
chore: update deps for v2.0.3

### PR DESCRIPTION
**Pull request by daylinmorgan**
Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ x] Ensured the license file is being packaged.

Closes #36

### CODE REVIEW

**Comment by theAeon** [comment]
unearth is pending merge here, for the record

https://github.com/conda-forge/staged-recipes/pull/20112#issuecomment-1220238667

**Comment by theAeon** [comment]
oh also @daylinmorgan you might want to include a dependency on filecache b/c conda is weird about bracketed pip dependencies. I got that one merged the other day.

**Comment by daylinmorgan** [comment]
@theAeon The "filecache" extra for `cachecontrol` is on `lockfile` though, right?

**Comment by theAeon** [comment]
I don't believe it is. Can you link me to where you're seeing that?

**Comment by daylinmorgan** [comment]
https://github.com/ionrock/cachecontrol/blob/6155c199438bfc3944a833f1dec6fb74134476f1/setup.py#L25

**Comment by theAeon** [comment]
oh, wow, I misread that horribly. Guess I didn't need to package filecache for conda after all. You're good.

**Comment by xhochy** [comment]
Is there any reason why you would need this old version? Otherwise, I would go with the bot PR #44 with the new version. With https://github.com/conda-incubator/grayskull/pull/377 the bot should also be able to make correct automated PRs for new versions again.

**Comment by daylinmorgan** [comment]
I think it's fine to just use the version in #44, but the recipe there still has extra dependencies.

PDM no longer requires:
```yaml
- click
- chardet
- idna
- wheel
```

And two should have python version constraints added:
```yaml
- tomli >=1.1.0  # [py<311]
- importlib-metadata  # [py<38]
```

**Pull request closed without merging**
